services:
  - type: worker
    name: youtube-chat-monitor
    runtime: python
    env: python
    region: frankfurt # или другой регион
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python monitor.py"
    envVars:
      - key: YOUTUBE_API_KEY
        sync: false
      - key: YOUTUBE_VIDEO_ID
        sync: false
      - key: TARGET_USER
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false